### ISSUE TITLE
how use axios.default.headers.common set token

### ISSUE THREAD

**Issue by vichbb** [benhason1/nestjs-http-promise#18]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**
In  HttpModule.registerAsync, I injected request to set the token in the header, but when I was using httpservice.get or httpservice. post with other config , my token will be overwritten. How to set  axios.default.headers.common in HttpModule.registerAsync. If you can answer my question, thank you very much!

**Additional context**

**Comment by vichbb** [comment]
Mention it. This tool is great! I like it very much!

**Comment by benhason1** [comment]
Hi, thx for the feedback.
Can you add an example code that you’re trying and having issues with?

**Comment by vichbb** [comment]
> Hi, thx for the feedback. Can you add an example code that you’re trying and having issues with?

Thank you very much for your reply! Due to the tight project time, I adopted another scheme: wrap a new httpservice in the outer layer of httpservice And inject request into newhttpservice, which solves my problem. Thank you again! Is there any simple way to use Axios interceptor in this toolkit?

**Comment by benhason1** [comment]
The `HttpService` exposes its `axios` instance directly via `get axiosRef()`.
With it, you can add an [axios interceptor](https://github.com/axios/axios#interceptors).

```ts
this.httpService.axiosRef.interceptors.request.use(config => { /*...*/ return config })
```

Hope it helps, if not you can always reopen the issue 😃

**Comment by vichbb** [comment]
> 

Thank you very much！
