### ISSUE TITLE
Support for latest @nestjs/common v10.x.x (and possible update/bump package dependencies) 

### ISSUE THREAD

**Issue by sprijk** [benhason1/nestjs-http-promise#21]
**Is your feature request related to a problem? Please describe.**
This package currently requires nestjs 7, 8, or 9, and therefore creates a dependency issue when installing for a nestjs 10.x.x project.

**Describe the solution you'd like**
Would love to use this package with support for nestjs 10! would be great to also have all dependencies bumped.

**Describe alternatives you've considered**
Alternatively, I'd use @nestjs/axios and convert each observable to a promise.

**Comment by benhason1** [comment]
I can't see any reason to use @nestjs/axios and convert each observable to a promise, if you can give more details why you think its a better approach I will love to hear it.

**Comment by sprijk** [comment]
you can ignore that :)
but would you consider updating to nestjs 10?

**Comment by benhason1** [comment]
Yes of course, will happen in the coming days
